version: '3'

services:
    app:
        build: ./docker
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www
        expose:
            - "9000"

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - ./:/var/www
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
